# Generated by Django 5.2.17 on 2026-08-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers come first on the page.')),
                ('is_published', models.BooleanField(default=True, help_text='Unpublished items stay in the admin but vanish from the site.')),
                ('label', models.CharField(max_length=60)),
                ('href', models.CharField(help_text='Site-relative path, e.g. /about-us — or a full external URL.', max_length=200)),
                ('show_in_header', models.BooleanField(default=True)),
                ('show_in_footer', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Navigation link',
                'verbose_name_plural': 'Navigation links',
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_name', models.CharField(default='SALON', help_text='The wordmark in the header, the mobile menu and the badge.', max_length=60)),
                ('badge_caption', models.CharField(default="We Don't Keep Our Beauty Secrets", help_text='Set around the circular badge in Follow Us and the footer.', max_length=120)),
                ('meta_title', models.CharField(default='Salon — Always Make Room for a Little Beauty in Your Life', help_text='Browser tab title and the default social-share title.', max_length=200)),
                ('meta_description', models.TextField(default='Hair, beauty and spa treatments in London. Book an appointment or browse the service menu.')),
                ('nav_cta_label', models.CharField(default='Book Now', max_length=60)),
                ('nav_cta_href', models.CharField(default='/book-appointment', max_length=200)),
                ('copyright_text', models.CharField(default='2023 Salon All rights reserved', max_length=200)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers come first on the page.')),
                ('is_published', models.BooleanField(default=True, help_text='Unpublished items stay in the admin but vanish from the site.')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('x', 'X / Twitter')], default='facebook', help_text='Picks the icon. Facebook and Instagram have drawn icons on the site; other platforms fall back to a label.', max_length=20)),
                ('url', models.URLField()),
                ('label', models.CharField(blank=True, help_text='Accessible link label. Defaults to “Salon on <platform>”.', max_length=80)),
            ],
            options={
                'verbose_name': 'Social link',
                'verbose_name_plural': 'Social links',
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
    ]
