# Generated by Django 5.2.17 on 2026-08-13 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='copyright_text',
            field=models.CharField(default='2026 Salon All rights reserved', max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='meta_description',
            field=models.TextField(default='Premium hair, beauty and spa treatments in Kathmandu, Nepal. Book an appointment or browse the service menu.'),
        ),
    ]
