# Generated by Django 5.2.17 on 2026-08-13 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_sitesettings_copyright_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='esewa_note',
            field=models.CharField(default='Scan with eSewa, pay, then upload your payment screenshot below.', help_text='Instruction shown beside the QR on the booking form.', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='esewa_qr',
            field=models.ImageField(blank=True, help_text="Your eSewa QR code. Shown on the booking form; leave empty to hide that step's image.", upload_to='payment/'),
        ),
    ]
