# Generated by Django 5.2.17 on 2026-08-13 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings_esewa_note_sitesettings_esewa_qr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='nav_cta_href',
            field=models.CharField(default='/services', max_length=200),
        ),
    ]
