# Generated by Django 5.2.17 on 2026-08-13 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_sitesettings_nav_cta_href'),
        # Drop the old columns only after their values have been copied to
        # bookings.BookingSection.
        ('bookings', '0006_carry_esewa_to_booking_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='esewa_note',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='esewa_qr',
        ),
    ]
