# Generated by Django 5.0.14 on 2026-08-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_sitesettings_esewa_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text="Shown in the header and the mobile menu instead of the brand name. Leave empty to show the brand name as text. It is drawn against a dark bar and scaled to the bar's height, so a wide image with a transparent background reads best.", upload_to='brand/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo_url',
            field=models.CharField(blank=True, help_text='Leave empty if you uploaded a file — the upload is always used. Only fill this in to point at an image hosted somewhere else.', max_length=500),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='brand_name',
            field=models.CharField(default='SALON', help_text='The wordmark. Shown in the header and the mobile menu only when no logo is uploaded above — but the badge always uses it, and it names the logo for screen readers, so keep it filled in either way.', max_length=60),
        ),
    ]
