# Generated by Django 5.0.14 on 2026-08-16 11:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sitesettings_logo_sitesettings_logo_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='logo_height',
            field=models.PositiveSmallIntegerField(default=48, help_text='Height of the logo in the header, in pixels. This is the one that makes a square or round mark bigger. The header bar grows with it.', validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(160)]),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo_width',
            field=models.PositiveSmallIntegerField(default=200, help_text='Most the logo may spread sideways, in pixels. Raise it for a wide wordmark; a square mark will not use the extra room.', validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(480)]),
        ),
    ]
