# Generated by Django 5.0.14 on 2026-08-16 12:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sitesettings_logo_height_sitesettings_logo_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='logo_height_mobile',
            field=models.PositiveSmallIntegerField(default=36, help_text='Same, on phones and tablets (under 1280px wide). Usually smaller: the bar is the same height but the screen it crosses is a third as wide, so a mark sized for a monitor eats the whole width.', validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(160)]),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo_height',
            field=models.PositiveSmallIntegerField(default=48, help_text='Height of the logo in the header on a computer, in pixels. This is the one that makes a square or round mark bigger. The header bar grows with it, and the page below moves down to match.', validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(160)]),
        ),
    ]
