# Generated by Django 5.0.14 on 2026-08-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_sitesettings_logo_height_mobile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='logo_height',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='logo_height_mobile',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='logo_width',
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Shown in the header and the mobile menu instead of the brand name. Leave empty to show the brand name as text. It is scaled to a fixed height — 48px on a computer, 32px on a phone — with its proportions kept and a 180px cap on how wide it may spread. Nothing here needs sizing: upload a mark that reads at that height, with a transparent background, and it will sit correctly against the dark bar.', upload_to='brand/'),
        ),
    ]
