# Generated by Django 5.0.14 on 2026-08-18 09:10

import common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_sitesettings_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(default=False, help_text='Off means nothing is sent — bookings and enquiries are still saved and still appear below in the admin. Turn this on once the address and password are filled in and the test email arrives.', verbose_name='Send emails')),
                ('username', models.CharField(blank=True, help_text='The account mail is sent from, e.g. yoursalon@gmail.com.', max_length=254, verbose_name='Gmail address')),
                ('password', common.fields.EncryptedCharField(blank=True, help_text='NOT your Gmail password — Google refuses those. Create a 16-character App Password at myaccount.google.com/apppasswords (needs 2-Step Verification on the account first). Spaces are ignored, so paste it exactly as Google shows it. Stored encrypted; leave blank to keep the one already saved.', max_length=500, verbose_name='App password')),
                ('from_name', models.CharField(blank=True, help_text='Shown as the sender, e.g. "Salon Kathmandu". The address is always the Gmail account above — Google rewrites it otherwise.', max_length=100, verbose_name='Sender name')),
                ('notify_emails', models.TextField(blank=True, help_text='Who is told when a booking or an enquiry arrives. One address per line, or separated by commas. Leave blank to use the Gmail address above.', verbose_name='Send notifications to')),
                ('host', models.CharField(blank=True, help_text='Leave blank for Gmail (smtp.gmail.com).', max_length=255, verbose_name='SMTP server')),
                ('port', models.PositiveIntegerField(blank=True, help_text='Leave blank to match the encryption setting — 587 or 465.', null=True)),
                ('security', models.CharField(choices=[('starttls', 'STARTTLS — port 587 (Gmail)'), ('ssl', 'SSL/TLS — port 465'), ('none', 'None — unencrypted')], default='starttls', help_text='Gmail uses STARTTLS on port 587.', max_length=10)),
                ('last_test_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_test_ok', models.BooleanField(default=False, editable=False)),
                ('last_test_detail', models.TextField(blank=True, editable=False)),
            ],
            options={
                'verbose_name': 'Email / SMTP settings',
                'verbose_name_plural': 'Email / SMTP settings',
            },
        ),
    ]
