# Generated by Django 5.0.14 on 2026-08-18 09:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_emailsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsettings',
            name='host',
            field=models.CharField(blank=True, help_text='Optional. Leave blank for Gmail (smtp.gmail.com).', max_length=255, verbose_name='SMTP server'),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='port',
            field=models.PositiveIntegerField(blank=True, help_text='Optional. Leave blank and the port follows the encryption setting below — 587 for STARTTLS, 465 for SSL.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)]),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='security',
            field=models.CharField(choices=[('starttls', 'STARTTLS — port 587 (Gmail)'), ('ssl', 'SSL/TLS — port 465'), ('none', 'None — unencrypted')], default='starttls', help_text='Already set correctly for Gmail (STARTTLS). Only change it for a provider that asks for something else.', max_length=10),
        ),
    ]
