# Generated by Django 5.0.14 on 2026-08-19 07:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_emailsettings_host_alter_emailsettings_port_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('booking', 'Booking'), ('enquiry', 'Enquiry')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.CharField(blank=True, max_length=255)),
                ('target_app_label', models.CharField(max_length=100)),
                ('target_model', models.CharField(max_length=100)),
                ('target_object_id', models.CharField(max_length=64)),
                ('read_by', models.ManyToManyField(blank=True, related_name='read_admin_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin notification',
                'verbose_name_plural': 'Admin notifications',
                'ordering': ('-created_at', '-pk'),
                'indexes': [models.Index(fields=['-created_at'], name='core_adminn_created_0bade4_idx')],
            },
        ),
    ]
