# Generated by Django 5.0.14 on 2026-08-23 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_adminnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='copyright_text',
            field=models.CharField(default='© 2026 AJ Salon. All rights reserved.', max_length=200),
        ),
    ]
