# Generated by Django 5.0.14 on 2026-08-23 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_update_copyright_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='brand_name',
            field=models.CharField(default='AJ Salon', help_text='The wordmark. Shown in the header and the mobile menu only when no logo is uploaded above — but the badge always uses it, and it names the logo for screen readers, so keep it filled in either way.', max_length=60),
        ),
    ]
