# Generated by Django 5.0.14 on 2026-09-01 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_update_brand_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='meta_title',
            field=models.CharField(default='AJ Salon — Always Make Room for a Little Beauty in Your Life', help_text='Browser tab title and the default social-share title.', max_length=200),
        ),
    ]
