# Generated by Django 5.2.17 on 2026-08-12 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsSeenOnSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heading', models.CharField(default='As seen On', max_length=120)),
                ('quote', models.TextField(default='The place with its constant excellence, soul, and style', help_text='Rendered inside typographic quotes; do not type your own.')),
                ('attribution', models.CharField(blank=True, help_text='Optional. Shown under the quote.', max_length=120)),
                ('cta_label', models.CharField(default='Learn More', max_length=60)),
                ('cta_href', models.CharField(default='/about-us', max_length=200)),
            ],
            options={
                'verbose_name': 'As seen on',
                'verbose_name_plural': 'As seen on',
            },
        ),
        migrations.CreateModel(
            name='ClassesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heading_top', models.CharField(default='Classes Designed', max_length=120)),
                ('heading_bottom', models.CharField(default='For You', max_length=120)),
                ('marquee_phrase', models.CharField(default='START FAST • FINISH FASTER • PUSH HARDER • GET STRONGER • NEVER QUIT • BREAK LIMITS', help_text='Repeated across the strip. Separate items with • .', max_length=300)),
            ],
            options={
                'verbose_name': 'Classes',
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='ContactColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers come first on the page.')),
                ('is_published', models.BooleanField(default=True, help_text='Unpublished items stay in the admin but vanish from the site.')),
                ('heading', models.CharField(max_length=60)),
                ('icon', models.CharField(choices=[('phone', 'Phone'), ('clock', 'Clock'), ('pin', 'Map pin')], default='phone', max_length=20)),
                ('body', models.TextField(help_text='One line per line. Line breaks are preserved.')),
            ],
            options={
                'verbose_name': 'Contact column',
                'verbose_name_plural': 'Contact columns',
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FollowUsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heading', models.CharField(default='Follow Us', max_length=120)),
                ('body', models.TextField(default='Don’t miss promotions, follow us for the latest news')),
            ],
            options={
                'verbose_name': 'Follow us',
                'verbose_name_plural': 'Follow us',
            },
        ),
        migrations.CreateModel(
            name='FooterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_heading', models.CharField(default='Contact Us', max_length=120)),
                ('contact_body', models.TextField(default='Don’t miss promotions, follow us for the latest news')),
            ],
            options={
                'verbose_name': 'Footer',
                'verbose_name_plural': 'Footer',
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eyebrow', models.CharField(default='Welcome To Choppers', max_length=120)),
                ('headline_line_1', models.CharField(default='Best Hair Salon For A', max_length=120)),
                ('headline_line_2', models.CharField(default='Professional Look', max_length=120)),
                ('body', models.TextField(default='Choppers offers high performance customized facials to provide you with visible results.')),
                ('primary_cta_label', models.CharField(default='Book Now', max_length=60)),
                ('primary_cta_href', models.CharField(default='/book-appointment', max_length=200)),
                ('secondary_cta_label', models.CharField(default='All Services', max_length=60)),
                ('secondary_cta_href', models.CharField(default='/services', max_length=200)),
                ('background_image', models.ImageField(blank=True, upload_to='hero/')),
                ('background_image_url', models.CharField(blank=True, default='/images/hero-texture.jpg', help_text='Used when no file is uploaded above. A full https:// URL, or a path served by the frontend such as /images/hero-texture.jpg.', max_length=500)),
                ('stylist_image', models.ImageField(blank=True, upload_to='hero/')),
                ('stylist_image_url', models.CharField(blank=True, default='/images/hero-stylist.png', help_text='Used when no file is uploaded above. A full https:// URL, or a path served by the frontend such as /images/hero-texture.jpg.', max_length=500)),
                ('stylist_image_alt', models.CharField(default='A barber trimming the hair of a smiling client in a black cape', max_length=200)),
                ('watermark_image', models.ImageField(blank=True, upload_to='hero/')),
                ('watermark_image_url', models.CharField(blank=True, default='/images/choppers-mark.png', help_text='Used when no file is uploaded above. A full https:// URL, or a path served by the frontend such as /images/hero-texture.jpg.', max_length=500)),
            ],
            options={
                'verbose_name': 'Hero',
                'verbose_name_plural': 'Hero',
            },
        ),
        migrations.CreateModel(
            name='MotivationSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True, help_text='Untick to drop the whole band from the page.')),
            ],
            options={
                'verbose_name': 'Motivation lines',
                'verbose_name_plural': 'Motivation lines',
            },
        ),
        migrations.CreateModel(
            name='OurStorySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heading', models.CharField(default='Our Story', max_length=120)),
                ('body', models.TextField(default='We started as a small beauty studio in Pakistan. Our main idea was to create the best beauty studio in the world. Can there be compromises in the best studio in the world? Our answer is always no, we care about the best quality, we hire the best specialists and provide the best customer service. This approach allowed us to grow and create awesome team that is passionate about everything we do.')),
                ('cta_label', models.CharField(default='Learn More', max_length=60)),
                ('cta_href', models.CharField(default='/about-us', max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='story/')),
                ('image_url', models.CharField(blank=True, default='/images/salon-artist.webp', help_text='Used when no file is uploaded above. A full https:// URL, or a path served by the frontend such as /images/hero-texture.jpg.', max_length=500)),
                ('image_alt', models.CharField(default='Stylist holding a set of makeup brushes', max_length=200)),
            ],
            options={
                'verbose_name': 'Our story',
                'verbose_name_plural': 'Our story',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers come first on the page.')),
                ('is_published', models.BooleanField(default=True, help_text='Unpublished items stay in the admin but vanish from the site.')),
                ('label', models.CharField(max_length=80)),
                ('icon', models.CharField(choices=[('hair', 'Hair'), ('makeup', 'Makeup'), ('manicure-pedicure', 'Manicure & pedicure'), ('skincare', 'Skincare'), ('facial', 'Facial')], default='hair', max_length=40)),
                ('icon_image', models.ImageField(blank=True, help_text='Optional. Overrides the built-in icon above.', upload_to='services/')),
                ('href', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True, help_text='Not shown on the landing page; for a services page.')),
                ('price_from', models.DecimalField(blank=True, decimal_places=2, help_text='Optional. Shown as a “from” price where the design has one.', max_digits=8, null=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceMenuSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heading', models.CharField(default='Service Menu', max_length=120)),
                ('body', models.TextField(default='Get your nails done for great mood. Simple pleasures can make your week, not just day.')),
                ('cta_label', models.CharField(default='View Service Menu', max_length=60)),
                ('cta_href', models.CharField(default='/service-menu', max_length=200)),
            ],
            options={
                'verbose_name': 'Service menu',
                'verbose_name_plural': 'Service menu',
            },
        ),
        migrations.CreateModel(
            name='ClassCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers come first on the page.')),
                ('is_published', models.BooleanField(default=True, help_text='Unpublished items stay in the admin but vanish from the site.')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(help_text='A line break here becomes a line break on the card.', max_length=80)),
                ('href', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='classes/')),
                ('image_url', models.CharField(blank=True, help_text='Used when no file is uploaded. The seeded cards point at Cloudinary.', max_length=500)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='sections.classessection')),
            ],
            options={
                'verbose_name': 'Class card',
                'verbose_name_plural': 'Class cards',
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MotivationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers come first on the page.')),
                ('is_published', models.BooleanField(default=True, help_text='Unpublished items stay in the admin but vanish from the site.')),
                ('text', models.CharField(max_length=120)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sections.motivationsection')),
            ],
            options={
                'verbose_name': 'Motivation line',
                'verbose_name_plural': 'Motivation lines',
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
    ]
