# Generated by Django 5.2.17 on 2026-08-12 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GallerySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heading', models.CharField(default='Dribbble', max_length=120)),
                ('body', models.TextField(default='Like a lion’s roar echoing through\nthe jungle, a hint of our creative\nminds emerges.', help_text='Line breaks are kept from tablet up and collapse to spaces on a phone, where the measure is too narrow to break by hand.')),
                ('cta_label', models.CharField(default='View Dribbble', max_length=60)),
                ('cta_href', models.CharField(default='#', max_length=200)),
                ('is_published', models.BooleanField(default=True, help_text='Untick to drop the whole band from the page.')),
            ],
            options={
                'verbose_name': 'Gallery grid',
                'verbose_name_plural': 'Gallery grid',
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers come first on the page.')),
                ('is_published', models.BooleanField(default=True, help_text='Unpublished items stay in the admin but vanish from the site.')),
                ('image', models.ImageField(blank=True, upload_to='gallery/')),
                ('image_url', models.CharField(blank=True, help_text='Used when no file is uploaded above. A full https:// URL, or a path served by the frontend such as /images/hero-texture.jpg.', max_length=500)),
                ('alt', models.CharField(help_text='Describe the picture for screen readers and failed loads.', max_length=200)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sections.gallerysection')),
            ],
            options={
                'verbose_name': 'Gallery image',
                'verbose_name_plural': 'Gallery images',
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
    ]
