# Generated by Django 5.2.17 on 2026-08-13 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_gallerysection_galleryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classessection',
            name='heading_top',
            field=models.CharField(default='Services Designed', max_length=120),
        ),
        migrations.AlterField(
            model_name='classessection',
            name='marquee_phrase',
            field=models.CharField(default='LOOK GOOD • FEEL CONFIDENT • SHINE BRIGHT • EXPRESS YOURSELF • BE BEAUTIFUL • STAY RADIANT', help_text='Repeated across the strip. Separate items with • .', max_length=300),
        ),
        migrations.AlterField(
            model_name='gallerysection',
            name='body',
            field=models.TextField(default='Capturing elegance and artistry,\nwitness the transformations that\ndefine our craft.', help_text='Line breaks are kept from tablet up and collapse to spaces on a phone, where the measure is too narrow to break by hand.'),
        ),
        migrations.AlterField(
            model_name='gallerysection',
            name='cta_label',
            field=models.CharField(default='View Gallery', max_length=60),
        ),
        migrations.AlterField(
            model_name='gallerysection',
            name='heading',
            field=models.CharField(default='Our Speciality', max_length=120),
        ),
    ]
