# Generated by Django 5.2.17 on 2026-08-13 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0003_alter_classessection_heading_top_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourstorysection',
            name='body',
            field=models.TextField(default='We started as a small beauty salon in Kathmandu, Nepal. Our vision was to create a premium salon experience where beauty meets excellence. We believe in using only the finest products and techniques to help our clients look and feel their absolute best. Our team of expert stylists and beauty professionals are passionate about transforming your look and boosting your confidence with every visit.'),
        ),
    ]
