# Generated by Django 5.2.17 on 2026-08-13 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0004_alter_ourstorysection_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classessection',
            name='heading_bottom',
            field=models.CharField(default='In The Chair', max_length=120),
        ),
        migrations.AlterField(
            model_name='classessection',
            name='heading_top',
            field=models.CharField(default='Moments Captured', max_length=120),
        ),
        migrations.AlterField(
            model_name='classessection',
            name='marquee_phrase',
            field=models.CharField(default='FRESH CUTS • SHARP FADES • CLEAN LINES • EVERY CHAIR • EVERY DAY • REAL MOMENTS', help_text='Repeated across the strip. Separate items with • .', max_length=300),
        ),
    ]
