# Generated by Django 5.2.17 on 2026-08-13 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0005_alter_classessection_heading_bottom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersection',
            name='cta_href',
            field=models.CharField(default='/services', max_length=200),
        ),
        migrations.AddField(
            model_name='footersection',
            name='cta_label',
            field=models.CharField(default='Book a seat', max_length=60),
        ),
        migrations.AddField(
            model_name='footersection',
            name='email',
            field=models.EmailField(default='info@beautysalon.com', max_length=254),
        ),
        migrations.AddField(
            model_name='footersection',
            name='heading_line1',
            field=models.CharField(default='TIME', max_length=40),
        ),
        migrations.AddField(
            model_name='footersection',
            name='heading_line2',
            field=models.CharField(default='TO', max_length=40),
        ),
        migrations.AddField(
            model_name='footersection',
            name='heading_line3',
            field=models.CharField(default='ROAR!', max_length=40),
        ),
        migrations.AddField(
            model_name='footersection',
            name='phone',
            field=models.CharField(default='070 9485 7568', max_length=40),
        ),
    ]
