# Generated by Django 5.2.17 on 2026-08-13 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0006_footersection_cta_href_footersection_cta_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='primary_cta_href',
            field=models.CharField(default='/services', max_length=200),
        ),
        migrations.AlterField(
            model_name='servicemenusection',
            name='cta_href',
            field=models.CharField(default='/services', max_length=200),
        ),
    ]
