# Generated by Django 5.2.17 on 2026-08-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0007_alter_herosection_primary_cta_href_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='background_image_url',
            field=models.CharField(blank=True, default='', help_text='Used when no file is uploaded above. A full https:// URL, or a path served by the frontend such as /images/hero-texture.jpg.', max_length=500),
        ),
    ]
