# Generated by Django 5.2.17 on 2026-08-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0008_alter_herosection_background_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, upload_to='services/'),
        ),
        migrations.AddField(
            model_name='service',
            name='image_url',
            field=models.CharField(blank=True, help_text='Used when no file is uploaded above. A full https:// URL, or a path served by the frontend such as /images/hero-texture.jpg.', max_length=500),
        ),
    ]
