# Generated by Django 5.2.17 on 2026-08-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0009_service_image_service_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhoWeAreSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heading_line_1', models.CharField(default='WHO', max_length=40)),
                ('heading_line_2', models.CharField(default='WE ARE', max_length=40)),
                ('lead', models.TextField(default='A Kathmandu salon built on craft — every cut shaped to the person in the chair, not to a catalogue.', help_text='The large paragraph under the heading.')),
                ('body', models.TextField(default='Our stylists train year-round on cuts, colour and care, so the chair you sit in is the same standard every visit.', help_text='The smaller paragraph set against the right edge.')),
                ('cta_label', models.CharField(default='About us', max_length=60)),
                ('cta_href', models.CharField(default='/about-us', max_length=200)),
                ('is_published', models.BooleanField(default=True, help_text='Untick to drop the whole band from the page.')),
            ],
            options={
                'verbose_name': 'Who we are',
                'verbose_name_plural': 'Who we are',
            },
        ),
        migrations.DeleteModel(
            name='ServiceMenuSection',
        ),
    ]
