# Generated by Django 5.2.17 on 2026-08-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0010_whowearesection_delete_servicemenusection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image_url',
            field=models.CharField(blank=True, help_text='Leave empty if you uploaded a file — the upload is always used. Only fill this in to point at an image hosted somewhere else.', max_length=500),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='background_image_url',
            field=models.CharField(blank=True, default='', help_text='Leave empty if you uploaded a file — the upload is always used. Only fill this in to point at an image hosted somewhere else.', max_length=500),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='stylist_image_url',
            field=models.CharField(blank=True, default='/images/hero-stylist.png', help_text='Leave empty if you uploaded a file — the upload is always used. Only fill this in to point at an image hosted somewhere else.', max_length=500),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='watermark_image_url',
            field=models.CharField(blank=True, default='/images/choppers-mark.png', help_text='Leave empty if you uploaded a file — the upload is always used. Only fill this in to point at an image hosted somewhere else.', max_length=500),
        ),
        migrations.AlterField(
            model_name='ourstorysection',
            name='image_url',
            field=models.CharField(blank=True, default='/images/salon-artist.webp', help_text='Leave empty if you uploaded a file — the upload is always used. Only fill this in to point at an image hosted somewhere else.', max_length=500),
        ),
        migrations.AlterField(
            model_name='service',
            name='image_url',
            field=models.CharField(blank=True, help_text='Leave empty if you uploaded a file — the upload is always used. Only fill this in to point at an image hosted somewhere else.', max_length=500),
        ),
    ]
