# Generated by Django 5.2.17 on 2026-08-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0011_alter_galleryimage_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='background_color',
            field=models.CharField(default='#0a0a0a', help_text='Behind the whole hero band. Default is (#0a0a0a) — paste that back to restore it.', max_length=32),
        ),
        migrations.AddField(
            model_name='herosection',
            name='body_color',
            field=models.CharField(default='#9a9a9a', help_text='The paragraph under the headline. Default is (#9a9a9a) — paste that back to restore it.', max_length=32),
        ),
        migrations.AddField(
            model_name='herosection',
            name='eyebrow_color',
            field=models.CharField(default='#fbb034', help_text='The small line above the headline. Default is (#fbb034) — paste that back to restore it.', max_length=32),
        ),
        migrations.AddField(
            model_name='herosection',
            name='heading_color',
            field=models.CharField(default='#ffffff', help_text='The big two-line headline. Default is (#ffffff) — paste that back to restore it.', max_length=32),
        ),
        migrations.AddField(
            model_name='herosection',
            name='primary_button_bg',
            field=models.CharField(default='#c7ff3d', help_text='Fill of the first button. Default is (#c7ff3d) — paste that back to restore it.', max_length=32),
        ),
        migrations.AddField(
            model_name='herosection',
            name='primary_button_text',
            field=models.CharField(default='#000000', help_text='Text on the first button. Default is (#000000) — paste that back to restore it.', max_length=32),
        ),
        migrations.AddField(
            model_name='herosection',
            name='secondary_button_color',
            field=models.CharField(default='#c7ff3d', help_text='Outline and text of the second button; it fills with this on hover. Default is (#c7ff3d) — paste that back to restore it.', max_length=32),
        ),
    ]
