# Generated by Django 5.2.17 on 2026-08-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0012_herosection_background_color_herosection_body_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footersection',
            name='heading_line3',
            field=models.CharField(default='SHINE', max_length=40),
        ),
    ]
