# Generated by Django 5.0.14 on 2026-08-15 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0013_alter_footersection_heading_line3'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers come first on the page.')),
                ('is_published', models.BooleanField(default=True, help_text='Unpublished items stay in the admin but vanish from the site.')),
                ('heading', models.CharField(max_length=120)),
                ('body', models.TextField(blank=True, help_text='Prose for this column. Leave empty if the column is a bullet list and add the bullets on this page instead. A blank line starts a new paragraph.')),
            ],
            options={
                'verbose_name': 'About column',
                'verbose_name_plural': 'About columns',
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('established_year', models.PositiveIntegerField(default=2018, help_text='Used to work out how long the salon has been open. Write {years} in any text below and it is replaced by that number.')),
                ('hero_title', models.CharField(default='Beauty Salon Experience', max_length=160)),
                ('hero_date', models.CharField(default='In Kathmandu since 2018', help_text='Small line under the hero title.', max_length=160)),
                ('hero_scroll_prompt', models.CharField(default='Scroll to Explore Our Salon', max_length=160)),
                ('hero_video_url', models.CharField(blank=True, default='https://res.cloudinary.com/ufiebboc/video/upload/f_auto,q_auto/hfjpk00y9fqeznekhrh9', help_text='The video that expands as the visitor scrolls.', max_length=500)),
                ('hero_poster_url', models.CharField(blank=True, default='https://res.cloudinary.com/ufiebboc/image/upload/v1786268716/devis-gym/devis/IMG_7361.JPG.jpg', help_text='Still frame shown before the video plays.', max_length=500)),
                ('hero_bg_image', models.ImageField(blank=True, upload_to='about/')),
                ('hero_bg_image_url', models.CharField(blank=True, default='https://res.cloudinary.com/ufiebboc/image/upload/v1786268716/devis-gym/devis/IMG_7361.JPG.jpg', help_text='Leave empty if you uploaded a file — the upload is always used. Only fill this in to point at an image hosted somewhere else.', max_length=500)),
                ('eyebrow', models.CharField(default='About Our Salon', max_length=120)),
                ('heading_line_1', models.CharField(default='More Than', max_length=120)),
                ('heading_line_2', models.CharField(default='Just A Salon.', help_text='Rendered in the accent colour.', max_length=120)),
                ('intro_body', models.TextField(default='Our Salon provides a unique way to engage with our beauty community through personalized experiences. Located in the heart of Kathmandu, we have been transforming lives for over {years} years with our commitment to exceptional beauty services and personalized styling solutions. Our state-of-the-art facility combines modern techniques with expert guidance from 6+ certified stylists who are passionate about helping you achieve your beauty goals. Open Sunday through Friday from 10:00 AM to 8:00 PM, we offer flexible hours to fit your schedule. With a supportive community of 500+ happy clients, we offer more than just a beauty service - we provide a complete beauty experience designed to unlock your true confidence.')),
                ('team_heading', models.CharField(default='Meet Our Team', max_length=160)),
                ('team_body', models.TextField(default='Our certified beauty professionals are passionate about helping you look and feel your best. With years of experience and specialized training in the latest beauty trends and techniques, they provide personalized styling and treatments tailored to your unique needs.')),
                ('cta_heading_lead', models.CharField(default='Ready to', max_length=120)),
                ('cta_heading_accent', models.CharField(default='Book Your Appointment?', help_text='Rendered in the accent colour, following the lead above.', max_length=120)),
                ('cta_body', models.TextField(default='Join our community and experience what beauty excellence feels like. No commitments, no pressure - just stunning results.')),
                ('cta_primary_label', models.CharField(default='Contact Us', max_length=80)),
                ('cta_primary_href', models.CharField(default='/contact', max_length=200)),
                ('cta_secondary_label', models.CharField(default='View Membership', max_length=80)),
                ('cta_secondary_href', models.CharField(default='/#membership', max_length=200)),
                ('instagram_handle', models.CharField(default='@beautysalon_kathmandu', help_text='Shown down the side of the Instagram strip.', max_length=120)),
            ],
            options={
                'verbose_name': 'About us',
                'verbose_name_plural': 'About us',
            },
        ),
        migrations.CreateModel(
            name='AboutColumnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers come first on the page.')),
                ('is_published', models.BooleanField(default=True, help_text='Unpublished items stay in the admin but vanish from the site.')),
                ('text', models.CharField(max_length=200)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sections.aboutcolumn')),
            ],
            options={
                'verbose_name': 'Column bullet',
                'verbose_name_plural': 'Column bullets',
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='aboutcolumn',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='sections.aboutsection'),
        ),
        migrations.CreateModel(
            name='AboutStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers come first on the page.')),
                ('is_published', models.BooleanField(default=True, help_text='Unpublished items stay in the admin but vanish from the site.')),
                ('value', models.CharField(help_text='Counts up on screen when it contains a number. {years} works here too -- use it for the years-in-business tile so it cannot go stale.', max_length=40)),
                ('label', models.CharField(max_length=120)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='sections.aboutsection')),
            ],
            options={
                'verbose_name': 'About stat',
                'verbose_name_plural': 'About stats',
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers come first on the page.')),
                ('is_published', models.BooleanField(default=True, help_text='Unpublished items stay in the admin but vanish from the site.')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(max_length=120)),
                ('image', models.ImageField(blank=True, upload_to='team/')),
                ('image_url', models.CharField(blank=True, help_text='Leave empty if you uploaded a file — the upload is always used. Only fill this in to point at an image hosted somewhere else.', max_length=500)),
                ('facebook_url', models.CharField(blank=True, help_text='Leave empty to hide this icon for this person.', max_length=300)),
                ('twitter_url', models.CharField(blank=True, max_length=300)),
                ('youtube_url', models.CharField(blank=True, max_length=300)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='sections.aboutsection')),
            ],
            options={
                'verbose_name': 'Team member',
                'verbose_name_plural': 'Team members',
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
    ]
