# Generated by Django 5.0.14 on 2026-08-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0015_seed_about_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='hero_poster_url',
            field=models.CharField(blank=True, default='https://res.cloudinary.com/ufiebboc/image/upload/v1786268716/devis-gym/devis/IMG_7361.JPG.jpg', help_text='Optional. Shown inside the video frame for the moment before the video data arrives; without it that moment is a black rectangle. A still taken from the video itself looks best, because nothing jumps when playback starts. Leave empty to skip it.', max_length=500),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='hero_video_url',
            field=models.CharField(blank=True, default='https://res.cloudinary.com/ufiebboc/video/upload/f_auto,q_auto/hfjpk00y9fqeznekhrh9', help_text="The clip that starts small and expands as the visitor scrolls. This is the section's whole effect.", max_length=500),
        ),
    ]
