# Generated by Django 5.0.14 on 2026-08-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0016_alter_aboutsection_hero_poster_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='hero_poster_url',
            field=models.CharField(blank=True, default='https://res.cloudinary.com/ufiebboc/image/upload/v1786268716/devis-gym/devis/IMG_7361.JPG.jpg', help_text='Leave this empty unless you want a different image here. Empty means the background image below is used, which is almost always what you want. Fill it in only to show a still taken from the video itself, so nothing jumps when playback starts.', max_length=500),
        ),
    ]
