# Generated by Django 5.0.14 on 2026-08-15 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0017_alter_aboutsection_hero_poster_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutsection',
            name='hero_poster_url',
        ),
    ]
