# Generated by Django 5.0.14 on 2026-08-15 14:36

import common.storage
import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0018_remove_aboutsection_hero_poster_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='hero_video',
            field=models.FileField(blank=True, help_text='Upload the clip here. It goes to Cloudinary when the account is configured, and to the local media folder otherwise. An upload always wins over the URL below.', storage=common.storage.video_storage, upload_to='about/video/', validators=[common.validators.validate_video_upload]),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='hero_video_url',
            field=models.CharField(blank=True, default='https://res.cloudinary.com/ufiebboc/video/upload/f_auto,q_auto/hfjpk00y9fqeznekhrh9', help_text='Leave empty if you uploaded a file above -- the upload is always used. Only fill this in to point at a video hosted somewhere else.', max_length=500),
        ),
    ]
