# Generated by Django 5.0.14 on 2026-08-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0019_aboutsection_hero_video_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactcolumn',
            options={'ordering': ['order', 'pk'], 'verbose_name': 'Contact detail', 'verbose_name_plural': 'Contact details'},
        ),
        migrations.AlterField(
            model_name='contactcolumn',
            name='heading',
            field=models.CharField(help_text='Keep the headings “Location” and “Hours” spelled that way. The Contact Us page and the search-engine listing look each record up by this name, so renaming one hides the address or the opening hours from the site.', max_length=60),
        ),
    ]
