# Generated by Django 5.0.14 on 2026-08-16 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0020_alter_contactcolumn_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactColumn',
        ),
    ]
