# Generated by Django 5.0.14 on 2026-08-20 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0021_delete_contactcolumn'),
    ]

    operations = [
        migrations.AddField(
            model_name='classcard',
            name='video_uid',
            field=models.CharField(blank=True, help_text='Filled in automatically when a clip is uploaded above. Paste an id here only to point this card at a video already in the Stream account.', max_length=64, verbose_name='Cloudflare Stream id'),
        ),
        migrations.AddField(
            model_name='classcard',
            name='video_url',
            field=models.CharField(blank=True, help_text='An escape hatch for a clip hosted somewhere other than Cloudflare Stream -- an .m3u8 or .mp4 address. The Stream id above wins if both are filled in.', max_length=500, verbose_name='Video URL'),
        ),
    ]
