# Generated by Django 5.0.14 on 2026-08-20 06:25

import common.storage
import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0022_classcard_video_uid_classcard_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='classcard',
            name='video_upload',
            field=models.FileField(blank=True, help_text='Set by the upload box. Goes to Cloudinary when Cloudflare Stream is not configured.', storage=common.storage.video_storage, upload_to='classes/video/', validators=[common.validators.validate_video_upload], verbose_name='Uploaded clip'),
        ),
    ]
