# Generated by Django 5.0.14 on 2026-08-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0023_classcard_video_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classcard',
            name='video_uid',
        ),
        migrations.RemoveField(
            model_name='classcard',
            name='video_upload',
        ),
        migrations.AlterField(
            model_name='classcard',
            name='video_url',
            field=models.CharField(blank=True, help_text='The address of a clip hosted somewhere else -- a Cloudflare or Cloudinary video URL, or any direct .mp4 or .m3u8 link. While this is filled in it replaces the photo on this card.', max_length=500, verbose_name='Video URL'),
        ),
    ]
