# Generated by Django 5.0.14 on 2026-08-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0024_remove_classcard_video_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='hero_bg_image',
            field=models.ImageField(blank=True, help_text='DEPRECATED: No longer used in the frontend. The hero now uses video only with a dark overlay for text readability.', upload_to='about/'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='hero_bg_image_url',
            field=models.CharField(blank=True, default='', help_text='DEPRECATED: No longer used in the frontend. The hero now uses video only.', max_length=500),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='hero_date',
            field=models.CharField(default='In Kathmandu since 2018', help_text='Subtitle displayed under the hero title.', max_length=160),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='hero_scroll_prompt',
            field=models.CharField(default='Scroll to Explore Our Salon', help_text='Text prompt shown with animated mouse icon and down arrow. Leave filled to show scroll indicators, or clear to hide them.', max_length=160),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='hero_title',
            field=models.CharField(default='AJ SALON EXPERIENCE', help_text='Main heading displayed on the video hero (split across 2 lines).', max_length=160),
        ),
        migrations.AlterField(
            model_name='gallerysection',
            name='cta_href',
            field=models.CharField(default='/services', max_length=200),
        ),
        migrations.AlterField(
            model_name='gallerysection',
            name='cta_label',
            field=models.CharField(default='View Services', max_length=60),
        ),
    ]
