# Generated by Django 5.0.14 on 2026-09-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0025_update_about_hero_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutsection',
            name='hero_bg_image',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='hero_bg_image_url',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='hero_video',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='hero_video_url',
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Upload the hero image here. It goes to Cloudinary when the account is configured, and to the local media folder otherwise. An upload always wins over the URL below.', upload_to='about/hero/'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='hero_image_url',
            field=models.CharField(blank=True, default='', help_text='Leave empty if you uploaded a file above -- the upload is always used. Only fill this in to point at an image hosted somewhere else.', max_length=500),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='hero_title',
            field=models.CharField(default='AJ SALON EXPERIENCE', help_text='Main heading displayed on the hero (split across 2 lines).', max_length=160),
        ),
    ]
