# Generated by Django 5.2.17 on 2026-09-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0026_change_about_hero_to_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='watermark_image_url',
            field=models.CharField(blank=True, default='', help_text='Leave empty if you uploaded a file — the upload is always used. Only fill this in to point at an image hosted somewhere else.', max_length=500),
        ),
    ]
