"""`manage.py backup`.

A backup command that has never been run is not a backup strategy, so these
run it for real against a temp directory and check the output can actually be
loaded back.
"""

import json
import shutil
import tempfile
import zipfile
from io import StringIO
from pathlib import Path

from django.core.management import call_command
from django.test import TestCase, override_settings

from bookings.models import Appointment
from core.models import NavLink


class BackupCommandTests(TestCase):
    def setUp(self):
        self.out_dir = tempfile.mkdtemp()
        self.private = tempfile.mkdtemp()
        self.addCleanup(shutil.rmtree, self.out_dir, ignore_errors=True)
        self.addCleanup(shutil.rmtree, self.private, ignore_errors=True)

    def run_backup(self, **options):
        options.setdefault("output_dir", self.out_dir)
        with override_settings(PRIVATE_MEDIA_ROOT=self.private):
            call_command("backup", stdout=StringIO(), **options)
        return sorted(p.name for p in Path(self.out_dir).iterdir())

    def test_writes_a_database_dump(self):
        NavLink.objects.create(label="Home", href="/")
        files = self.run_backup()
        self.assertTrue(any(name.startswith("db-") for name in files))

    def test_the_dump_contains_the_content(self):
        NavLink.objects.create(label="Distinctive", href="/x")
        self.run_backup()

        dump = next(Path(self.out_dir).glob("db-*.json"))
        records = json.loads(dump.read_text(encoding="utf-8"))
        labels = [
            r["fields"]["label"] for r in records if r["model"] == "core.navlink"
        ]
        self.assertIn("Distinctive", labels)

    def test_sessions_are_excluded(self):
        """Restoring them would restore other people's logins."""
        NavLink.objects.create(label="Home", href="/")
        self.run_backup()

        dump = next(Path(self.out_dir).glob("db-*.json"))
        models = {r["model"] for r in json.loads(dump.read_text(encoding="utf-8"))}
        self.assertNotIn("sessions.session", models)
        self.assertNotIn("contenttypes.contenttype", models)

    def test_bookings_are_included(self):
        """They are the records that cannot be regenerated by seed_content."""
        Appointment.objects.create(name="Asha")
        self.run_backup()

        dump = next(Path(self.out_dir).glob("db-*.json"))
        models = {r["model"] for r in json.loads(dump.read_text(encoding="utf-8"))}
        self.assertIn("bookings.appointment", models)

    def test_private_media_is_archived(self):
        target = Path(self.private) / "payments" / "2026" / "08"
        target.mkdir(parents=True)
        (target / "proof.png").write_bytes(b"pretend png")

        files = self.run_backup()
        archive = next(n for n in files if n.startswith("private-media-"))

        with zipfile.ZipFile(Path(self.out_dir) / archive) as zf:
            self.assertIn("payments/2026/08/proof.png", zf.namelist())

    def test_empty_private_media_is_reported_not_archived(self):
        files = self.run_backup()
        self.assertFalse(any(n.startswith("private-media-") for n in files))

    def test_skip_media_leaves_the_files_alone(self):
        (Path(self.private) / "proof.png").write_bytes(b"x")
        files = self.run_backup(skip_media=True)
        self.assertFalse(any(n.startswith("private-media-") for n in files))

    def test_prune_keeps_only_the_most_recent(self):
        for _ in range(4):
            self.run_backup(keep=0)
        # Timestamps are per-second, so force distinct names.
        for index, path in enumerate(sorted(Path(self.out_dir).glob("db-*.json"))):
            path.rename(Path(self.out_dir) / f"db-2026010{index}-000000.json")

        self.run_backup(keep=2)
        remaining = sorted(Path(self.out_dir).glob("db-*.json"))
        self.assertEqual(len(remaining), 2)

    def test_keep_zero_retains_everything(self):
        self.run_backup(keep=0)
        for index, path in enumerate(sorted(Path(self.out_dir).glob("db-*.json"))):
            path.rename(Path(self.out_dir) / f"db-2026010{index}-000000.json")
        self.run_backup(keep=0)
        self.assertEqual(len(list(Path(self.out_dir).glob("db-*.json"))), 2)

    def test_creates_the_output_directory_if_missing(self):
        nested = str(Path(self.out_dir) / "deep" / "nested")
        with override_settings(PRIVATE_MEDIA_ROOT=self.private):
            call_command("backup", output_dir=nested, stdout=StringIO())
        self.assertTrue(list(Path(nested).glob("db-*.json")))

    def test_the_dump_can_be_loaded_back(self):
        """The only test that proves this is a backup and not just a file."""
        NavLink.objects.create(label="Restore me", href="/r")
        self.run_backup()
        dump = next(Path(self.out_dir).glob("db-*.json"))

        NavLink.objects.all().delete()
        call_command("loaddata", str(dump), stdout=StringIO(), verbosity=0)

        self.assertTrue(NavLink.objects.filter(label="Restore me").exists())
