# Generated by Django 5.2.17 on 2026-08-13 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers come first on the page.')),
                ('is_published', models.BooleanField(default=True, help_text='Unpublished items stay in the admin but vanish from the site.')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(blank=True, help_text='Shown under the name, e.g. "Senior stylist".', max_length=120)),
                ('photo', models.ImageField(blank=True, upload_to='barbers/')),
                ('bio', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Barber',
                'verbose_name_plural': 'Barbers',
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_screenshot',
            field=models.ImageField(blank=True, upload_to='payments/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='appointment',
            name='barber',
            field=models.ForeignKey(blank=True, help_text='Kept if the barber later leaves, so the record survives.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='bookings.barber'),
        ),
    ]
