# Generated by Django 5.2.17 on 2026-08-13 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_barber_appointment_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='working_days',
            field=models.CharField(blank=True, help_text='Free text, e.g. "Sun – Fri" or "Weekends only". Leave empty to hide.', max_length=120),
        ),
        migrations.AddField(
            model_name='barber',
            name='works_from',
            field=models.TimeField(blank=True, help_text='Start of their day, e.g. 10:00.', null=True),
        ),
        migrations.AddField(
            model_name='barber',
            name='works_to',
            field=models.TimeField(blank=True, help_text='End of their day, e.g. 19:00.', null=True),
        ),
    ]
