# Generated by Django 5.2.17 on 2026-08-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_barber_working_days_barber_works_from_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_heading', models.CharField(default='Choose your service', max_length=120)),
                ('barber_heading', models.CharField(default='Choose your barber', max_length=120)),
                ('details_heading', models.CharField(default='Your details', max_length=120)),
                ('payment_heading', models.CharField(default='Pay with eSewa', max_length=120)),
                ('service_step', models.CharField(default='Service', max_length=40)),
                ('barber_step', models.CharField(default='Barber', max_length=40)),
                ('details_step', models.CharField(default='Details', max_length=40)),
                ('payment_step', models.CharField(default='Payment', max_length=40)),
                ('submit_label', models.CharField(default='Submit booking', max_length=60)),
                ('success_heading', models.CharField(default='Booking request sent', max_length=120)),
            ],
            options={
                'verbose_name': 'Booking form',
                'verbose_name_plural': 'Booking form',
            },
        ),
    ]
