# Generated by Django 5.2.17 on 2026-08-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_bookingsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsection',
            name='esewa_note',
            field=models.CharField(default='Scan with eSewa, pay, then upload your payment screenshot below.', help_text='Instruction shown beside the QR.', max_length=200),
        ),
        migrations.AddField(
            model_name='bookingsection',
            name='esewa_qr',
            field=models.ImageField(blank=True, help_text="The salon's own eSewa QR code. Shown on the last step of the booking form. Leave empty and that step explains how to pay instead of showing a broken image.", upload_to='payment/'),
        ),
        migrations.AddField(
            model_name='bookingsection',
            name='payment_amount_note',
            field=models.CharField(blank=True, help_text='Optional line above the QR, e.g. "Pay a Rs 500 deposit to confirm your seat." Leave empty to hide it.', max_length=200),
        ),
    ]
