# Generated by Django 5.2.17 on 2026-08-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_carry_esewa_to_booking_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsection',
            name='page_heading',
            field=models.CharField(default='Book your seat', max_length=120),
        ),
        migrations.AddField(
            model_name='bookingsection',
            name='page_intro',
            field=models.TextField(default='Pick a service and a stylist, tell us when suits you, and we will confirm by phone.'),
        ),
    ]
