# Generated by Django 5.2.17 on 2026-08-13 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_bookingsection_page_heading_and_more'),
        ('sections', '0012_herosection_background_color_herosection_body_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order', 'pk'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sections.service',),
        ),
    ]
