# Generated by Django 5.2.17 on 2026-08-13 09:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingsection',
            name='payment_amount_note',
        ),
        migrations.AddField(
            model_name='bookingsection',
            name='deposit_percent',
            field=models.PositiveSmallIntegerField(default=100, help_text='How much of the service price to collect up front, as a percentage. 100 means the customer pays the full price to book; 30 means they pay a 30% deposit and the rest at the salon. The amount is worked out from the price of whichever service they picked, so it is never typed by hand.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
