# Generated by Django 5.2.17 on 2026-08-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_remove_bookingsection_payment_amount_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='clerk_user_id',
            field=models.CharField(blank=True, db_index=True, help_text='Clerk account id. Set automatically; not editable by the customer.', max_length=64),
        ),
    ]
