# Generated by Django 5.2.17 on 2026-08-13 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_appointment_clerk_user_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClerkProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clerk_user_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('providers', models.CharField(blank=True, help_text='Comma separated, as reported by Clerk.', max_length=200)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email_verified', models.BooleanField(default=False)),
                ('banned', models.BooleanField(default=False)),
                ('clerk_created_at', models.DateTimeField(blank=True, null=True)),
                ('last_sign_in_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clerk_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clerk account',
                'verbose_name_plural': 'Clerk accounts',
                'ordering': ['-last_sign_in_at', '-clerk_created_at'],
            },
        ),
    ]
