# Generated by Django 5.2.17 on 2026-08-13 17:55

import common.storage
import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_appointment_status_workflow'),
        ('sections', '0013_alter_footersection_heading_line3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='payment_screenshot',
            field=models.ImageField(blank=True, storage=common.storage.private_storage, upload_to='payments/%Y/%m/', validators=[common.validators.validate_upload]),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status', '-created_at'], name='appt_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['preferred_date'], name='appt_preferred_date_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['clerk_user_id', '-created_at'], name='appt_clerk_created_idx'),
        ),
    ]
