# Generated by Django 5.2.17 on 2026-08-13 18:35

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_alter_appointment_payment_screenshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='phone',
            field=models.CharField(blank=True, max_length=40, validators=[common.validators.validate_phone]),
        ),
    ]
