# Generated by Django 5.2.17 on 2026-08-14 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_alter_appointment_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='scheduled_date',
            field=models.DateField(blank=True, help_text='The date you want the customer to come in. Leave empty to accept the date they asked for.', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='scheduled_time',
            field=models.TimeField(blank=True, help_text='The time you want them to come in. Leave empty to accept the time they asked for. The customer sees this as soon as you approve the booking.', null=True),
        ),
    ]
