# Generated by Django 5.2.17 on 2026-08-14 05:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0015_appointment_scheduled_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsection',
            name='closes_at',
            field=models.TimeField(default=datetime.time(19, 0), help_text='Last appointment of the day. The latest time you can pick.'),
        ),
        migrations.AddField(
            model_name='bookingsection',
            name='opens_at',
            field=models.TimeField(default=datetime.time(9, 0), help_text='First appointment of the day. The earliest time you can pick.'),
        ),
        migrations.AddField(
            model_name='bookingsection',
            name='slot_minutes',
            field=models.PositiveSmallIntegerField(choices=[(15, 'Every 15 minutes'), (30, 'Every half hour'), (60, 'Every hour')], default=30, help_text='How far apart the times in the dropdown are.'),
        ),
    ]
