# Generated by Django 5.2.17 on 2026-08-14 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0016_bookingsection_closes_at_bookingsection_opens_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='is_available',
            field=models.BooleanField(default=True, help_text="Untick while this barber is away or fully booked. They stay on the site with an 'unavailable' badge and cannot be selected. To remove them from the site entirely, untick Is published instead.", verbose_name='Available for bookings'),
        ),
        migrations.AddField(
            model_name='barber',
            name='unavailable_note',
            field=models.CharField(blank=True, help_text='Shown on the card when unavailable, e.g. "Back on 20 August". Leave empty for a plain \'Not available\' badge.', max_length=120),
        ),
        migrations.AlterField(
            model_name='barber',
            name='works_from',
            field=models.TimeField(blank=True, help_text='Start of their day. Pick from the list.', null=True),
        ),
        migrations.AlterField(
            model_name='barber',
            name='works_to',
            field=models.TimeField(blank=True, help_text='End of their day. Pick from the list.', null=True),
        ),
    ]
