# Generated by Django 5.0.14 on 2026-08-16 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0017_barber_is_available_barber_unavailable_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='clerk_user_id',
            field=models.CharField(blank=True, help_text='Clerk account id. Set automatically; not editable by the customer.', max_length=64),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='order_id',
            field=models.CharField(blank=True, help_text='Created automatically on approval. Blank until then.', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reference',
            field=models.CharField(blank=True, help_text='Shown to the customer on submit. Generated automatically.', max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='clerkprofile',
            name='clerk_user_id',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
