# Generated by Django 5.0.14 on 2026-08-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0019_drop_stale_redundant_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='clerk_user_id',
            field=models.CharField(blank=True, help_text='Clerk account id. Set automatically; not editable by the sender.', max_length=64),
        ),
    ]
