# Generated by Django 5.0.14 on 2026-09-01 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0020_contactmessage_clerk_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers come first on the page.')),
                ('is_published', models.BooleanField(default=True, help_text='Unpublished items stay in the admin but vanish from the site.')),
                ('date', models.DateField(help_text='Which day this slot is available (YYYY-MM-DD)')),
                ('start_time', models.TimeField(help_text='Start time of this slot (e.g., 10:00)')),
                ('end_time', models.TimeField(help_text='End time of this slot (e.g., 11:00)')),
                ('is_booked', models.BooleanField(default=False, help_text='Check to mark this slot as booked (unavailable for customers)')),
                ('barber', models.ForeignKey(help_text='Which barber this time slot is for', on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='bookings.barber')),
            ],
            options={
                'verbose_name': 'Time Slot',
                'verbose_name_plural': 'Time Slots',
                'ordering': ['barber', 'date', 'start_time', 'order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='time_slot',
            field=models.ForeignKey(blank=True, help_text='The time slot selected for this appointment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='bookings.timeslot'),
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.UniqueConstraint(fields=('barber', 'date', 'start_time', 'end_time'), name='unique_barber_date_time_slot'),
        ),
    ]
