# Generated by Django 5.2.17 on 2026-09-16, then hand-edited to carry the data
# across: see `dates_to_weekdays`.

from django.db import migrations, models


def dates_to_weekdays(apps, schema_editor):
    """Fold dated slots down onto the weekday they fall on.

    Ordering matters here and is why this migration is not the one
    `makemigrations` wrote: that one dropped `date` before `weekday` existed,
    which would have thrown every slot's day away and left the whole timetable
    sitting on Sunday.

    Folding a diary into a week collides by definition -- three Sundays of the
    same 10am slot become three identical rows, and the new unique constraint
    is applied straight after this runs. So duplicates are merged rather than
    left to fail: the oldest row of each group is kept, any appointment
    pointing at one of its twins is moved onto it first, and only then are the
    twins deleted. Deleting them without that step would silently blank the
    slot on a real booking, because the FK is SET_NULL.
    """
    TimeSlot = apps.get_model("bookings", "TimeSlot")
    Appointment = apps.get_model("bookings", "Appointment")

    for slot in TimeSlot.objects.all().iterator():
        # `isoweekday()` counts Monday as 1 and Sunday as 7; the salon's week
        # starts on Sunday, so 7 wraps to 0. Mirrors `Weekday.from_date`.
        TimeSlot.objects.filter(pk=slot.pk).update(
            weekday=slot.date.isoweekday() % 7
        )

    seen = {}
    for slot in TimeSlot.objects.order_by("pk").iterator():
        key = (slot.barber_id, slot.weekday, slot.start_time, slot.end_time)
        keeper = seen.get(key)
        if keeper is None:
            seen[key] = slot.pk
            continue
        Appointment.objects.filter(time_slot_id=slot.pk).update(time_slot_id=keeper)
        slot.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0022_clerk_to_google_auth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['barber', 'weekday', 'start_time', 'order'], 'verbose_name': 'Time Slot', 'verbose_name_plural': 'Time Slots'},
        ),
        migrations.RemoveConstraint(
            model_name='timeslot',
            name='unique_barber_date_time_slot',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='weekday',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], default=0, help_text='Which day of the week this slot repeats on'),
        ),
        # Between the two schema edits, while both columns exist. Not reversible:
        # going back would need a real date for every slot, and the week it came
        # from is exactly what this throws away.
        migrations.RunPython(dates_to_weekdays, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='timeslot',
            name='date',
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='is_booked',
            field=models.BooleanField(default=False, help_text="Tick to take this time off the booking form. It applies to every week, not to a single date -- for one day off, untick 'Available for bookings' on the barber instead.", verbose_name='Closed'),
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.UniqueConstraint(fields=('barber', 'weekday', 'start_time', 'end_time'), name='unique_barber_weekday_time_slot'),
        ),
    ]
