"""Put every barber on the same five-a-day week.

This is a data migration rather than a note in the README because the salon's
own database is on Render, where nothing runs by hand: `build.sh` calls
`migrate` on every deploy, so shipping the seed as a migration is what makes it
actually reach production. It runs exactly once, on the deploy that carries it.

It replaces the timetable wholesale -- 0023 folded whatever dated slots existed
onto weekdays, which for a database with more than a week of history leaves a
thicket of odd times rather than a timetable anyone would choose. Wiping is the
point, not a side effect.

Real bookings are carried across. The `Appointment.time_slot` FK is SET_NULL,
so deleting slots would quietly blank the slot on a customer's booking; each one
is remembered first and relinked afterwards to the same time if it survived, or
to the nearest remaining time on the same day if it did not.

To change the shape of the week later, do not edit this file -- edit the slots
in the admin, or re-run the command this mirrors:

    python manage.py seed_time_slots --reset --per-day 5
"""

from datetime import date, datetime, time, timedelta

from django.db import migrations

#: How many bookable times each barber offers per day.
PER_DAY = 5

# Mirrors `BookingSection`'s own defaults. Historical models keep their fields
# but lose their methods, so `time_slots()` is not reachable here and the day
# has to be rebuilt from the three columns it is derived from.
DEFAULT_OPENS = time(9, 0)
DEFAULT_CLOSES = time(19, 0)
DEFAULT_STEP = 30


def day_ranges(opens, closes, step):
    """Every (start, end) the opening hours imply, `closes` included.

    Inclusive of the closing time because the field is described in the admin
    as the last appointment of the day, not the moment the door is locked.
    """
    anchor = date.today()
    first = opens.hour * 60 + opens.minute
    last = closes.hour * 60 + closes.minute
    if last < first:
        # Closing before opening is a typo. Returning nothing would seed an
        # empty timetable and leave the booking form permanently blank.
        return []

    ranges = []
    for minute in range(first, last + 1, step):
        start = time(minute // 60, minute % 60)
        end = (datetime.combine(anchor, start) + timedelta(minutes=step)).time()
        if end > start:
            ranges.append((start, end))
    return ranges


def pick_evenly(ranges, count):
    """Thin `ranges` to `count`, spread across the day rather than bunched.

    Same rule as `seed_time_slots.pick_evenly`: keep the first and last opening
    times as the endpoints and space the rest between them, so five slots on a
    9-to-7 day fall at 9:00, 11:30, 2:00, 4:30 and 7:00 instead of filling the
    morning and leaving the afternoon looking shut.
    """
    if count <= 0 or count >= len(ranges):
        return ranges
    if count == 1:
        return ranges[:1]
    last = len(ranges) - 1
    # `dict.fromkeys` keeps order while dropping the repeats that rounding can
    # produce when `count` approaches `len(ranges)`.
    indexes = dict.fromkeys(round(i * last / (count - 1)) for i in range(count))
    return [ranges[i] for i in indexes]


def seed_five_a_day(apps, schema_editor):
    TimeSlot = apps.get_model("bookings", "TimeSlot")
    Barber = apps.get_model("bookings", "Barber")
    BookingSection = apps.get_model("bookings", "BookingSection")
    Appointment = apps.get_model("bookings", "Appointment")

    barbers = list(Barber.objects.filter(is_published=True).order_by("order", "id"))
    if not barbers:
        # Nothing to hang a timetable off. Leaving the table untouched is
        # kinder than wiping it for a database that has not been set up yet.
        return

    section = BookingSection.objects.first()
    ranges = pick_evenly(
        day_ranges(
            getattr(section, "opens_at", None) or DEFAULT_OPENS,
            getattr(section, "closes_at", None) or DEFAULT_CLOSES,
            getattr(section, "slot_minutes", None) or DEFAULT_STEP,
        ),
        PER_DAY,
    )
    if not ranges:
        return

    # (appointment pk) -> where it pointed, so it can be found again after.
    links = {
        appointment.pk: (
            appointment.time_slot.barber_id,
            appointment.time_slot.weekday,
            appointment.time_slot.start_time,
        )
        for appointment in Appointment.objects.filter(
            time_slot__isnull=False
        ).select_related("time_slot")
    }

    TimeSlot.objects.all().delete()

    TimeSlot.objects.bulk_create(
        [
            TimeSlot(
                barber=barber,
                weekday=weekday,
                start_time=start,
                end_time=end,
                is_booked=False,
                is_published=True,
                # `order` follows the time, so a seeded week needs no hand
                # ordering in the admin.
                order=position,
            )
            for barber in barbers
            for weekday in range(7)
            for position, (start, end) in enumerate(ranges)
        ]
    )

    for pk, (barber_id, weekday, start) in links.items():
        same_day = list(
            TimeSlot.objects.filter(barber_id=barber_id, weekday=weekday)
        )
        if not same_day:
            continue
        wanted = start.hour * 60 + start.minute
        nearest = min(
            same_day,
            key=lambda slot: abs(
                (slot.start_time.hour * 60 + slot.start_time.minute) - wanted
            ),
        )
        Appointment.objects.filter(pk=pk).update(time_slot=nearest)


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0023_alter_timeslot_options_and_more"),
    ]

    operations = [
        # Not reversible: the timetable this replaces is exactly what it throws
        # away, and there is nothing to rebuild it from.
        migrations.RunPython(seed_five_a_day, migrations.RunPython.noop),
    ]
